dirs:
    output: output
    templates: templates
    posts: posts
gzip: yes
markdown_extras:
    - smarty-pants
site:
    title: blog.shilbert.com
    description: Scott Hilbert's personal blog
#    hostname: localhost:8000
#    prefix: /static
    hostname: blog.shilbert.com
posts_per_page: 2
rss_posts: 10
#favicon: favicon.ico