output_dir: output
templates_dir: templates
posts_dir: posts
gzip: yes
markdown_extras:
    - smarty-pants
title: blog.shilbert.com
description: Scott Hilbert's personal blog
hostname: localhost:8000
#prefix: /static
#hostname: blog.shilbert.com
posts_per_page: 2
rss: yes
rss_posts: 10
favicon: favicon.ico
