dirs:
    output: output
    templates: templates
    posts: posts
templates:
    post: post.html
    post_group: post_group.html
    archive: archive.html
gzip: no
markdown_extras:
    - smarty-pants
site:
    title: blog.shilbert.com
posts_per_page: 2